name: worker in action

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y python3
      
    - name: get key
      run: |
        echo ${{ secrets.KEY }} > files/mod/key.txt

    - name: start worker
      run: |
        cd files
        python3 worker.py
